[profile.default]
auto_detect_remappings=false
src = "src"
out = "out"
libs = ["lib"]
remappings = [ "@chainlink/=lib/chainlink/contracts/","@openzeppelin/=lib/openzeppelin-contracts/"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options